### ISSUE TITLE
When loading the first evaluation model, the model architechture is mismatch with the checkpoint

### ISSUE THREAD

**Issue by yangze68** [minghchen/CARL_code#1]
I place the 'checkpoint_epoch_00150.pth' into '~/tmp /scl_transformer_logs/checkpoints' 
following same routine of ReadMe to load checkpoints, the error presented below:
<img width="1182" alt="sp20220408_162138_519" src="https://user-images.githubusercontent.com/23077895/162395651-99f61891-a752-4932-a255-4adc44b0dae9.png">

How to solve it?
Thanks

**Comment by minghchen** [comment]
Thanks for pointing this out.
We find we used 2 layers transformer to get this checkpoint instead of 3 layers as in the config.
 So you can run this to load it.

`python -m torch.distributed.launch --nproc_per_node 1 evaluate.py --workdir ~/datasets --cfg_file ./configs/scl_transformer_config.yml --logdir ~/tmp/scl_transformer_logs --opt MODEL.EMBEDDER_MODEL.NUM_LAYERS 2`

Remember to remove the old config file before,

`rm -rf ~/tmp/scl_transformer_logs/config.yml`

I will update the config to be consistent with the checkpoint
